### model
model_name_or_path: tiiuae/falcon-7b-instruct

### method
stage: dpo
do_train: true
finetuning_type: lora
lora_target: all
pref_beta: 0.1
pref_loss: sigmoid  # [sigmoid (dpo), orpo, simpo]

### ddp
ddp_timeout: 180000000

### dataset
dataset: speech_preference_icl_dpo
template: falcon
cutoff_len: 1024
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/falcon-7b-instruct/lora/dpo-icl
logging_steps: 50
plot_loss: true
overwrite_output_dir: false

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 1
learning_rate: 5.0e-6
num_train_epochs: 5.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
report_to: wandb

### eval
val_size: 0.1
per_device_eval_batch_size: 4
eval_strategy: steps
eval_steps: 100
save_total_limit: 3
save_strategy: steps
save_steps: 100
greater_is_better: false
metric_for_best_model: loss