### model
model_name_or_path: allenai/OLMo-7B-Instruct-hf

### method
stage: rm
do_train: true
finetuning_type: lora
lora_target: all

### ddp
ddp_timeout: 180000000
# deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
dataset: speech_preference
template: olmo
cutoff_len: 1024
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/olmo-7b-instruct/lora/reward
logging_steps: 10
save_steps: 50
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 8
gradient_accumulation_steps: 2
learning_rate: 5.0e-6
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
fp16: true
bf16: true
bf16_full_eval: true
report_to: wandb

### eval
val_size: 0.1
per_device_eval_batch_size: 8
eval_strategy: steps
eval_steps: 50
save_total_limit: 3
save_strategy: steps
save_steps: 50
greater_is_better: false
metric_for_best_model: loss

